### ISSUE TITLE
Error with `Sunry Murder Recording Enhancement` mod

### ISSUE THREAD

**Issue by th3w1zard1** [NickHugi/PyKotor#16]
```
[8/4/2023 2:15:19 PM] [Error] Traceback (most recent call last):
[8/4/2023 2:15:19 PM] Warning: A file named manm26ae.mod already exists in the Modules folder. Skipping file...
[8/4/2023 2:15:19 PM] Note: Replacing file k_pman_planet43.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file man26_bigcomp.dlg in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file plc_hotelcomp.dlg in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Adding file smre_closesunrydor.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_elassa.utc in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_fadein.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_fadeout.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_kill.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_killelassa.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_opendoor.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_opendoor2.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_rec_c.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_spawn_elas.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_spawn_sunry.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_sun_fin.dlg in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_sun_rec.dlg in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_sun_rec.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_sunry.utc in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file smre_term_conv.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] [Error]   File "pykotorcli.py", line 80, in <module>
[8/4/2023 2:15:19 PM] Note: Replacing file smre_wait1.ncs in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] [Error]   File "pykotor\tslpatcher\config.py", line 187, in install
[8/4/2023 2:15:19 PM] Note: Replacing file plc_hotelcomp.utp in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Replacing file plc_hotelscomp.utp in the manm26ae.MOD archive...
[8/4/2023 2:15:19 PM] Note: Patching m26ae.git in the modules\manm26ae.MOD folder.
[8/4/2023 2:15:19 PM] [Error] AttributeError: 'NoneType' object has no attribute 'data'
[8/4/2023 2:15:19 PM] [Error] [20572] Failed to execute script 'pykotorcli' due to unhandled exception!
```

**Comment by th3w1zard1** [comment]
TSLPatcher output if it helps:
```
 • Installation started 8/4/2023 3:34:45 PM...
 • Installing unmodified files...
 • Warning: A file named manm26ae.mod already exists in the Modules folder. Skipping file...
 • Saving unaltered backup copy of destination file manm26ae.MOD in C:\Users\boden\Documents\k1 mods\SMRE Version 3.0\SMRE\backup\.
 • Adding file k_pman_planet43.ncs to the Modules\manm26ae.MOD archive...
 • Replacing file man26_bigcomp.dlg in the Modules\manm26ae.MOD archive...
 • Adding file plc_hotelcomp.dlg to the Modules\manm26ae.MOD archive...
 • Adding file smre_closesunrydor.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_elassa.utc to the Modules\manm26ae.MOD archive...
 • Adding file smre_fadein.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_fadeout.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_kill.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_killelassa.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_opendoor.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_opendoor2.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_rec_c.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_spawn_elas.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_spawn_sunry.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_sun_fin.dlg to the Modules\manm26ae.MOD archive...
 • Adding file smre_sun_rec.dlg to the Modules\manm26ae.MOD archive...
 • Adding file smre_sun_rec.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_sunry.utc to the Modules\manm26ae.MOD archive...
 • Adding file smre_term_conv.ncs to the Modules\manm26ae.MOD archive...
 • Adding file smre_wait1.ncs to the Modules\manm26ae.MOD archive...
 • Adding file plc_hotelcomp.utp to the Modules\manm26ae.MOD archive...
 • Adding file plc_hotelscomp.utp to the Modules\manm26ae.MOD archive...
 • Modifying GFF format files...
 • File "m26ae.git" already exists in archive "manm26ae.MOD", modifying existing file...
 • Modifying GFF file m26ae.git...
 • Added new field to GFF file m26ae.git...
 • Added new field to GFF file m26ae.git...
 • Added new field to GFF file m26ae.git...
 • Added new field to GFF file m26ae.git...
 • Added new field to GFF file m26ae.git...
 • Finished updating GFF file "m26ae.git" in "modules\manm26ae.MOD"...
 • Saving modified file "m26ae.git" in archive "manm26ae.MOD".
 • Done. Changes have been applied, but 1 warnings were encountered.
```

**Comment by th3w1zard1** [comment]
Possibly related to #8?
