### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by th3w1zard1** [NickHugi/PyKotor#8]
```
[Note] Adding file plc_hotelscomp.utp in the manm26ae.MOD archive...
[Note] Patching m26ae.git in the modules\manm26ae.MOD folder.

[7/1/2023 10:03:34 PM] Traceback (most recent call last):
  File "pykotorcli.py", line 66, in <module>
  File "pykotor\tslpatcher\config.py", line 186, in install
AttributeError: 'NoneType' object has no attribute 'data'
```

config.ini:
```
; =====================================================[v1.0.5b1]====
; TSLPATCHER - GENERATED MODIFICATIONS FILE (1/27/2009)
; ===================================================================
; This file is automatically generated and as such has no formatting
; to speak of. You can insert blank lines between sections (but NOT
; between keys within a section!) and add comment lines starting
; with semicolon to make it more readable without breaking anything.
; -------------------------------------------------------------------

[Settings]
FileExists=1
WindowCaption=K1 Utility Armbands
ConfirmMessage=Did you read the ReadMe carefully?
LogLevel=3
InstallerMode=1
BackupFiles=1
PlaintextLog=0
LookupGameFolder=0
LookupGameNumber=1
SaveProcessedScripts=0


[TLKList]


[InstallList]
install_folder0=Modules
install_folder1=Modules\manm26ae.MOD


[2DAList]


[GFFList]
File0=m26ae.git


[CompileList]


[SSFList]


; ===================================================================

[gff_sa_ope_doo_PropertiesList_0_0]
FieldType=Struct
Path=PropertiesList
Label=
TypeId=0
AddField0=gff_sa_ope_doo_PropertyName_0
AddField1=gff_sa_ope_doo_Subtype_0
AddField2=gff_sa_ope_doo_CostTable_0
AddField3=gff_sa_ope_doo_CostValue_0
AddField4=gff_sa_ope_doo_Param1_0
AddField5=gff_sa_ope_doo_Param1Value_0
AddField6=gff_sa_ope_doo_ChanceAppear_0
[gff_sa_ope_doo_PropertyName_0]
FieldType=Word
Label=PropertyName
Value=10
[gff_sa_ope_doo_Subtype_0]
FieldType=Word
Label=Subtype
Value=2DAMEMORY1
[gff_sa_ope_doo_CostTable_0]
FieldType=Byte
Label=CostTable
Value=3
[gff_sa_ope_doo_CostValue_0]
FieldType=Word
Label=CostValue
Value=13
[gff_sa_ope_doo_Param1_0]
FieldType=Byte
Label=Param1
Value=255
[gff_sa_ope_doo_Param1Value_0]
FieldType=Byte
Label=Param1Value
Value=0
[gff_sa_ope_doo_ChanceAppear_0]
FieldType=Byte
Label=ChanceAppear
Value=100
[gff_sa_ori_arm_PropertiesList_0_0]
FieldType=Struct
Path=PropertiesList
Label=
TypeId=0
AddField0=gff_sa_ori_arm_PropertyName_0
AddField1=gff_sa_ori_arm_Subtype_0
AddField2=gff_sa_ori_arm_CostTable_0
AddField3=gff_sa_ori_arm_CostValue_0
AddField4=gff_sa_ori_arm_Param1_0
AddField5=gff_sa_ori_arm_Param1Value_0
AddField6=gff_sa_ori_arm_ChanceAppear_0
[gff_sa_ori_arm_PropertyName_0]
FieldType=Word
Label=PropertyName
Value=10
[gff_sa_ori_arm_Subtype_0]
FieldType=Word
Label=Subtype
Value=2DAMEMORY2
[gff_sa_ori_arm_CostTable_0]
FieldType=Byte
Label=CostTable
Value=3
[gff_sa_ori_arm_CostValue_0]
FieldType=Word
Label=CostValue
Value=13
[gff_sa_ori_arm_Param1_0]
FieldType=Byte
Label=Param1
Value=255
[gff_sa_ori_arm_Param1Value_0]
FieldType=Byte
Label=Param1Value
Value=0
[gff_sa_ori_arm_ChanceAppear_0]
FieldType=Byte
Label=ChanceAppear
Value=100
[gff_m01aa_Placeable List_60_0]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m01aa_TemplateResRef_0
AddField1=gff_m01aa_X_0
AddField2=gff_m01aa_Y_0
AddField3=gff_m01aa_Z_0
AddField4=gff_m01aa_Bearing_0
[gff_m01aa_TemplateResRef_0]
FieldType=ResRef
Label=TemplateResRef
Value=sa_uti_arm
[gff_m01aa_X_0]
FieldType=Float
Label=X
Value=11.8500003814697
[gff_m01aa_Y_0]
FieldType=Float
Label=Y
Value=15.9099998474121
[gff_m01aa_Z_0]
FieldType=Float
Label=Z
Value=-1.26999998092651
[gff_m01aa_Bearing_0]
FieldType=Float
Label=Bearing
Value=0
[m26ae.git]
AddField0=gff_m26ae_Placeable List_43_0
AddField1=gff_m26ae_Placeable List_44_0
AddField2=gff_m26ae_Placeable List_45_0
AddField3=gff_m26ae_Placeable List_46_0
CameraList\16\Orientation=0.122737869620323|0|0|0.992439150810242
AddField4=gff_m26ae_CameraList_19_0
!Destination=modules\manm26ae.MOD
[gff_m26ae_Placeable List_43_0]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_0
AddField1=gff_m26ae_X_0
AddField2=gff_m26ae_Y_0
AddField3=gff_m26ae_Z_0
AddField4=gff_m26ae_Bearing_0
[gff_m26ae_TemplateResRef_0]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelscomp
[gff_m26ae_X_0]
FieldType=Float
Label=X
Value=21
[gff_m26ae_Y_0]
FieldType=Float
Label=Y
Value=37.422420501709
[gff_m26ae_Z_0]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_0]
FieldType=Float
Label=Bearing
Value=1.57878005504608
[gff_m26ae_Placeable List_44_0]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_1
AddField1=gff_m26ae_X_1
AddField2=gff_m26ae_Y_1
AddField3=gff_m26ae_Z_1
AddField4=gff_m26ae_Bearing_1
[gff_m26ae_TemplateResRef_1]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_1]
FieldType=Float
Label=X
Value=5.44999980926514
[gff_m26ae_Y_1]
FieldType=Float
Label=Y
Value=36.8073883056641
[gff_m26ae_Z_1]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_1]
FieldType=Float
Label=Bearing
Value=4.69497013092041
[gff_m26ae_Placeable List_45_0]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_2
AddField1=gff_m26ae_X_2
AddField2=gff_m26ae_Y_2
AddField3=gff_m26ae_Z_2
AddField4=gff_m26ae_Bearing_2
[gff_m26ae_TemplateResRef_2]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_2]
FieldType=Float
Label=X
Value=21
[gff_m26ae_Y_2]
FieldType=Float
Label=Y
Value=47.3524208068848
[gff_m26ae_Z_2]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_2]
FieldType=Float
Label=Bearing
Value=1.57878005504608
[gff_m26ae_Placeable List_46_0]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_3
AddField1=gff_m26ae_X_3
AddField2=gff_m26ae_Y_3
AddField3=gff_m26ae_Z_3
AddField4=gff_m26ae_Bearing_3
[gff_m26ae_TemplateResRef_3]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_3]
FieldType=Float
Label=X
Value=19.5557098388672
[gff_m26ae_Y_3]
FieldType=Float
Label=Y
Value=65.870002746582
[gff_m26ae_Z_3]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_3]
FieldType=Float
Label=Bearing
Value=0.00441000005230308
[gff_m26ae_CameraList_19_0]
FieldType=Struct
Path=CameraList
Label=
TypeId=14
AddField0=gff_m26ae_CameraID_0
AddField1=gff_m26ae_Position_0
AddField2=gff_m26ae_Pitch_0
AddField3=gff_m26ae_MicRange_0
AddField4=gff_m26ae_Orientation_0
AddField5=gff_m26ae_Height_0
AddField6=gff_m26ae_FieldOfView_0
[gff_m26ae_CameraID_0]
FieldType=Int
Label=CameraID
Value=21
[gff_m26ae_Position_0]
FieldType=Position
Label=Position
Value=21.3220901489258|40.1263618469238|57.5034408569336
[gff_m26ae_Pitch_0]
FieldType=Float
Label=Pitch
Value=80
[gff_m26ae_MicRange_0]
FieldType=Float
Label=MicRange
Value=0
[gff_m26ae_Orientation_0]
FieldType=Orientation
Label=Orientation
Value=0.145659998059273|0|0|-0.989340007305145
[gff_m26ae_Height_0]
FieldType=Float
Label=Height
Value=1.5
[gff_m26ae_FieldOfView_0]
FieldType=Float
Label=FieldOfView
Value=55
[install_folder0]
File0=manm26ae.mod
[install_folder1]
Replace0=k_pman_planet43.ncs
Replace1=man26_bigcomp.dlg
Replace2=plc_hotelcomp.dlg
Replace3=smre_closesunrydor.ncs
Replace4=smre_elassa.utc
Replace5=smre_fadein.ncs
Replace6=smre_fadeout.ncs
Replace7=smre_kill.ncs
Replace8=smre_killelassa.ncs
Replace9=smre_opendoor.ncs
Replace10=smre_opendoor2.ncs
Replace11=smre_rec_c.ncs
Replace12=smre_spawn_elas.ncs
Replace13=smre_spawn_sunry.ncs
Replace14=smre_sun_fin.dlg
Replace15=smre_sun_rec.dlg
Replace16=smre_sun_rec.ncs
Replace17=smre_sunry.utc
Replace18=smre_term_conv.ncs
Replace19=smre_wait1.ncs
Replace20=plc_hotelcomp.utp
Replace21=plc_hotelscomp.utp
[gff_m26ae_Placeable List_43_1]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_4
AddField1=gff_m26ae_X_4
AddField2=gff_m26ae_Y_4
AddField3=gff_m26ae_Z_4
AddField4=gff_m26ae_Bearing_4
[gff_m26ae_TemplateResRef_4]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelscomp
[gff_m26ae_X_4]
FieldType=Float
Label=X
Value=21
[gff_m26ae_Y_4]
FieldType=Float
Label=Y
Value=37.422420501709
[gff_m26ae_Z_4]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_4]
FieldType=Float
Label=Bearing
Value=1.57878005504608
[gff_m26ae_Placeable List_44_1]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_5
AddField1=gff_m26ae_X_5
AddField2=gff_m26ae_Y_5
AddField3=gff_m26ae_Z_5
AddField4=gff_m26ae_Bearing_5
[gff_m26ae_TemplateResRef_5]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_5]
FieldType=Float
Label=X
Value=5.44999980926514
[gff_m26ae_Y_5]
FieldType=Float
Label=Y
Value=36.8073883056641
[gff_m26ae_Z_5]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_5]
FieldType=Float
Label=Bearing
Value=4.69497013092041
[gff_m26ae_Placeable List_45_1]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_6
AddField1=gff_m26ae_X_6
AddField2=gff_m26ae_Y_6
AddField3=gff_m26ae_Z_6
AddField4=gff_m26ae_Bearing_6
[gff_m26ae_TemplateResRef_6]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_6]
FieldType=Float
Label=X
Value=21
[gff_m26ae_Y_6]
FieldType=Float
Label=Y
Value=47.3524208068848
[gff_m26ae_Z_6]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_6]
FieldType=Float
Label=Bearing
Value=1.57878005504608
[gff_m26ae_Placeable List_46_1]
FieldType=Struct
Path=Placeable List
Label=
TypeId=9
AddField0=gff_m26ae_TemplateResRef_7
AddField1=gff_m26ae_X_7
AddField2=gff_m26ae_Y_7
AddField3=gff_m26ae_Z_7
AddField4=gff_m26ae_Bearing_7
[gff_m26ae_TemplateResRef_7]
FieldType=ResRef
Label=TemplateResRef
Value=plc_hotelcomp
[gff_m26ae_X_7]
FieldType=Float
Label=X
Value=19.5557098388672
[gff_m26ae_Y_7]
FieldType=Float
Label=Y
Value=65.870002746582
[gff_m26ae_Z_7]
FieldType=Float
Label=Z
Value=57.5034408569336
[gff_m26ae_Bearing_7]
FieldType=Float
Label=Bearing
Value=0.00441000005230308
[gff_m26ae_CameraList_19_1]
FieldType=Struct
Path=CameraList
Label=
TypeId=14
AddField0=gff_m26ae_CameraID_1
AddField1=gff_m26ae_Position_1
AddField2=gff_m26ae_Pitch_1
AddField3=gff_m26ae_MicRange_1
AddField4=gff_m26ae_Orientation_1
AddField5=gff_m26ae_Height_1
AddField6=gff_m26ae_FieldOfView_1
[gff_m26ae_CameraID_1]
FieldType=Int
Label=CameraID
Value=21
[gff_m26ae_Position_1]
FieldType=Position
Label=Position
Value=21.3220901489258|40.1263618469238|57.5034408569336
[gff_m26ae_Pitch_1]
FieldType=Float
Label=Pitch
Value=80
[gff_m26ae_MicRange_1]
FieldType=Float
Label=MicRange
Value=0
[gff_m26ae_Orientation_1]
FieldType=Orientation
Label=Orientation
Value=0.145659998059273|0|0|-0.989340007305145
[gff_m26ae_Height_1]
FieldType=Float
Label=Height
Value=1.5
[gff_m26ae_FieldOfView_1]
FieldType=Float
Label=FieldOfView
Value=55
changes.ini
11 KB
```

**Comment by th3w1zard1** [comment]
duplicate of #16 and also caused by #9
